version: '3'

services:
###> doctrine/doctrine-bundle ###
  db_rate_it:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer_rate_it:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
