version: '3'

services:
###> doctrine/doctrine-bundle ###
  db_rate_it:
    privileged: true
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: db_rate_it
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./.devops/db/data:/var/lib/postgresql/data:rw
    networks:
      - rate_it
  webserver_rate_it:
    privileged: true
    image: nginx:latest
    container_name: webserver_rate_it
    volumes:
      - ./:/var/www/html
      - ./.devops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - db_rate_it
      - php_fpm_rate_it
    networks:
      - rate_it
  php_fpm_rate_it:
    privileged: true
    build: .devops/php-fpm
    image: php_fpm_rate_it
    container_name: php_fpm_rate_it
    volumes:
      - ./:/var/www/html
    depends_on:
      - db_rate_it
    networks:
      - rate_it
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  rate_it:
    driver: bridge